language: node_js

sudo: false

node_js:
  - '4'

branches:
  only:
  - master

# cache:
#   directories:
#     - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_15db670b9b95_key -iv $encrypted_15db670b9b95_iv -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'acwong'
- git config --global user.email acwong00@gmail.com

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy

