language: node_js

sudo: false

node_js:
  - "4"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    package:
      - g++-4.8
  ssh_known_hosts: github.com

scripts:
  - hexo g

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
