menu:
    # Blog: /
    Archive: /archives/
    Tag: /tags/
    About: /about/
    # Weibo: http://weibo.com/achuang
    # GitHub: https://github.com/acwong00
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: acwong
duoshuo: 

# Analytics
# google-analytics:
ga: UA-65933410-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2014

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true

contact:
  mail: mailto:acwong00@gmail.com
  github: https://github.com/acwong00
  weibo: http://weibo.com/achuang
  douban: http://www.douban.com/people/acwong00/
