menu:
    # Blog: /
    Archive: /archives/
    Tag: /tags/
    About: /about/
    # Weibo: http://weibo.com/achuang
    # GitHub: https://github.com/acwong00
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: acwong
# duoshuo: acwong

# Analytics
# google-analytics:
ga: UA-51278674-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?671aac020a5151c07d7f2143a0f38ab4

# Copyright Infomation
startyear: 2014

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true

contact:
  mail: mailto:acwong00@gmail.com
  github: https://github.com/acwong00
  weibo: http://weibo.com/achuang
